# -*- coding: utf-8 -*-
"""reto_13_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cOT-cPAoQiDs9k5Tqip2BkwPR30zBLMX
"""

def diccionario(num_elementos):
  dic = {}
  for i in range(num_elementos):
    key = input("Ingresa el valor del key: ")
    bandera = True
    while bandera == True:
      if key in dic:
        print("ingresa otro valor, que ese ya esta")
        key = input("Ingresa el valor del key:: ")
      else:
        break
    valor = int(input("Ingresa 1 si quieres elementos elementos de texto \nIngresa 2 si quieres números enteros \nIngresa 3 si quieres flotantes \n "))
    while bandera == True:
      if valor in range(1,4):
        break
      else:
        print("INGRESE VALOR entre uno y tres")
        valor = int(input("Ingresa 1 si quieres elementos elementos de texto \nIngresa 2 si quieres números enteros \nIngresa 3 si quieres flotantes \n "))
    if valor == 1:
      valores = input("Ingresa el texto que desees, los números son menores que las letras, van bajo una regla extraña, mejor texto ")
    elif valor == 2:
      valores = int(input("Ingresa el número que desees ingregasr como valor correspondinete a la llave: "))
    elif valor == 3:
      valores = float(input("Ingresa el flotante que desees ingregasr como valor correspondinete a la llave: "))
    dic[key] = valores
  return dic

def crear_dic():
  dic_3 = {}
  bandera = True
  while bandera == True:
    for k,v in dic_1.items():
      if k in dic_3:
        continue
      else:
        dic_3[k] = v
    for k,v in dic_2.items():
      if k in dic_3:
        continue
      else:
        dic_3[k] = v
    bandera = False
    return dic_3


  return dic_3

if __name__ == "__main__":
  num_elementos = int(input("Cuantos elementos quieres para el diccionario 1: "))
  dic_1 = diccionario(num_elementos)
  print("Primer diccionario es: " +str(dic_1))
  num_elementos_b = int(input("Cuantos elementos quieres para el diccionario 2: "))
  dic_2 = diccionario(num_elementos_b)
  print("Segundo diccionario es: " +str(dic_2))
  tercer_dic = crear_dic()
  print("El diccionar junto es: " +str(tercer_dic))