# -*- coding: utf-8 -*-
"""reto_13_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gF-89StL3o6ZROzSDZvz4iq0tFwRmnr7
"""

import json #Importamos json
import requests # Requests
from pprint import pprint # Prety print

url = 'https://api.agify.io?name=' # Link de edad
url_1 = 'https://api.genderize.io?name=' # Link de genero
url_2 = 'https://api.nationalize.io?name=' # Link de nacionalidad

def predecir_edad(num : str): # Función que predice la edad
  peticion = requests.get(url+str(num)) # Busca en la web
  return json.loads(peticion.content) # Devuelve el json

def predecir_genero(num : str): # Función que predice genero
  peticion = requests.get(url_1+str(num)) # Busca en la web
  return json.loads(peticion.content) # Devuelve el json

def predecir_nacionalidad(num : str): # Función que predice genero
  peticion = requests.get(url_2+str(num)) # Busca en la web
  return json.loads(peticion.content) # Devuelve el json

def dic_unido(dic_1, dic_2, dic_3): # Función que une los diccionarios
  diccionario_nombre = {} #Diccionario vacio
  diccionario_nombre.update(dic_1) #Diccionario edad
  diccionario_nombre.update(dic_2) #Diccionario genero
  diccionario_nombre.update(dic_3) #Diccionario nacionalidad
  return diccionario_nombre

if __name__ == "__main__":
  Name = input("Ingresa un nombre: ") # Ingresa nombre
  respuesta = predecir_edad(Name) # Ejecutar función 1
  respuesta_ = predecir_genero(Name) # Ejecutar función 2
  respuesta_1 = predecir_nacionalidad(Name) # Ejecutar función 3
  nom_dic = dic_unido(respuesta, respuesta_, respuesta_1) # Ejecutar función 4
  print(Name) # Nombre
  pprint(nom_dic) #Pretty print