# -*- coding: utf-8 -*-
"""Reto_13_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z42gMQs2xuBl5G2a0pVmzxtN1bWoWbqT
"""

import json

with open('archivo.json', "r") as readFile:
  data = json.load(readFile) # Leer archivo

ingresa_ = input("Ingresa un deporte: ") # Pregunta deporte
ingresa_ = ingresa_.capitalize()
if ingresa_ == "futbol" or ingresa_ =="Futbol": # Casos especiales
  ingresa_ = "Fútbol"
if ingresa_ =="Bascket" or ingresa_ == "bascket":
  ingresa_ = "Baloncesto"

for persona, detalles in data.items(): #Busca e imprime usando for
  for uno, dos in detalles.items():
    if "deportes" in uno:
      for i in dos:
        if i == ingresa_:
          for tres, cuatro in detalles. items():
            if 'nombres' in tres:
              for cinco, seis in detalles.items():
                if 'apellidos' in cinco:
                  print("La persona " +str(cuatro)+ "" +str(seis)+ " juega " +str(ingresa_))

ingresa = int(input("Ingresa un número de edad: ")) # Ingresar edad
ingresa_2 = int(input("Ingresa otro númeor de edad: ")) # Ingresar edad 2

for persona, detalles in data.items(): #Busca e imprime usando for
  for uno, dos in detalles.items():
    if "edad" in uno:
      if ingresa > ingresa_2:
        if dos <= ingresa and dos >= ingresa_2:
          for tres, cuatro in detalles. items():
            if 'nombres' in tres:
              for cinco, seis in detalles.items():
                if 'apellidos' in cinco:
                  print("La persona " +str(cuatro)+ "" +str(seis)+ " esta entre " +str(ingresa_2)+ " y " +str(ingresa)+ " años")
      if ingresa < ingresa_2:
        if dos >= ingresa and dos <= ingresa_2:
          for tres, cuatro in detalles. items():
            if 'nombres' in tres:
              for cinco, seis in detalles.items():
                if 'apellidos' in cinco:
                  print("La persona " +str(cuatro)+ "" +str(seis)+ " esta entre " +str(ingresa)+ " y " +str(ingresa_2)+ " años")
      if ingresa == ingresa_2:
        if dos == ingresa and dos == ingresa_2:
          for tres, cuatro in detalles. items():
            if 'nombres' in tres:
              for cinco, seis in detalles.items():
                if 'apellidos' in cinco:
                  print("La persona " +str(cuatro)+ "" +str(seis)+ " tiene " +str(ingresa)+ " años")